# Generated by Django 5.1.3 on 2024-12-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='overall_total',
            field=models.IntegerField(default=0),
        ),
    ]
