# Generated by Django 5.1.3 on 2024-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_average_student_overall_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
