# Generated by Django 5.1.3 on 2024-12-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.student'),
        ),
    ]
