# Generated by Django 5.1.3 on 2024-12-20 22:27

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # Dynamically fetch the User model
    username = os.getenv('DJANGO_ADMIN_USERNAME')
    email = os.getenv('DJANGO_ADMIN_EMAIL')
    password = os.getenv('DJANGO_ADMIN_PASSWORD')

    if username and email and password:
        if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(
                username=username,
                email=email,
                password=password
            )
    else:
        raise ValueError("DJANGO_ADMIN_USERNAME, DJANGO_ADMIN_EMAIL, or DJANGO_ADMIN_PASSWORD environment variables are not set")

class Migration(migrations.Migration):
 
    dependencies = [
        ('api', '0012_alter_course_student_user'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]

